# Generated by Django 3.2.3 on 2021-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitor_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_city', models.CharField(max_length=100)),
            ],
        ),
    ]
