# Generated by Django 3.2.3 on 2021-07-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='hospital_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booked',
            name='vis_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
