# Generated by Django 3.2.3 on 2021-07-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
