# Generated by Django 3.2.3 on 2021-07-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_hospital_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
