# Generated by Django 3.2.3 on 2021-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_hospital_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='bedsubmit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_city', models.CharField(max_length=100)),
                ('beds', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
