# Generated by Django 3.2.3 on 2021-07-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_bedsubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsubmit',
            name='beds',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='bedsubmit',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
