# Generated by Django 3.2.3 on 2021-07-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210705_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedsubmit',
            name='available',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='bedsubmit',
            name='occupied',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
